all:
	xelatex smtchecker
	#bibtex smtchecker
	#xelatex smtchecker
	#xelatex smtchecker

clean:
	rm smtchecker.vrb smtchecker.toc smtchecker.snm smtchecker.out smtchecker.nav smtchecker.aux smtchecker.log smtchecker.blg smtchecker.bbl
